# 検証5-3c: invocation に pre-steps
version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - run: echo deploy
job-groups:
  deploy-group:
    jobs:
      - deploy
workflows:
  w:
    jobs:
      - deploy-group:
          pre-steps:
            - run: echo pre
