# 検証5-3e: invocation に override-with
version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - run: echo deploy
job-groups:
  deploy-group:
    jobs:
      - deploy
workflows:
  w:
    jobs:
      - deploy-group:
          override-with:
            executor: base-small
