version: 2.1

jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: exit

workflows:
  run:
    jobs:
      - build:
          filters:
            tags:
              only: "/^v(?!0\\.).*$/"
            branches:
              ignore: /.*/
